### ISSUE TITLE
Event UID Error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SurveillanceMyanmarApp#41] opened 2018-03-24 09:34 UTC
## User Report
Third time seeing this error and I am now trying to replicate this error. It happened when I create the case in offline, I do not know whether the error has link with case diagnosis or not but I entered 2 cases (P.f and P.v).

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot548696597.jpg)
## Device Info
```
Time Stamp: 2018-03-24T09:27:06 UTC
App Version: 1.0.4 (32)
Install Source: Package Installer
Android Version: 7.1.1 (25)
Device Manufacturer: SAMSUNG
Device Model: SM-N950F
Display Resolution: 2094x1080
Display Density (Actual): 420dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by myothetnaingwin** [comment] 2018-03-24 17:02
![Event UID Error.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab67fe17326ad0013b55330/125516c66e82c728ace21e0d46cd829f2d96c39ca6cdff66b64fff866b0a65633b0ba92e7391a172fd1723545b5e47a542585846f9aadd23a5b63c778e5508ed847f4366846c4ff8e7df46f554f832815d84bfb68b49c2e93424e7828a4f3a1a020ac4.jpg)
Please check

**Comment by ifoche** [comment] 2018-03-26 09:43
duplicate of #39

**Closed as completed** 2018-03-26 09:44 UTC
Labels: duplicate, invalid
