### ISSUE TITLE
case remains in unsent tab

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SurveillanceMyanmarApp#43] opened 2018-03-25 09:33 UTC
## User Report
case remains in unsent tab, but has already been sent to server

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot563365374.jpg)
## Device Info
```
Time Stamp: 2018-03-25T09:32:50 UTC
App Version: 1.0.4 (32)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: MOTOROLA
Device Model: MOTO G (4)
Display Resolution: 1776x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ifoche** [comment] 2018-03-26 09:51
Please, can you provide all the answers for this case that's unsent? Else, if you could send the DB, that would be perfect

**Comment by ifoche** [comment] 2018-03-27 08:17
This seems to be a duplicate of #38

**Closed as completed** 2018-03-27 08:18 UTC
Labels: duplicate, invalid
