### ISSUE TITLE
Event UID error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SurveillanceMyanmarApp#44] opened 2018-03-25 12:50 UTC
## User Report
This is my fourth time seeing this kind of error. Please fix this error before the next release.

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot719796533.jpg)
## Device Info
```
Time Stamp: 2018-03-25T12:48:49 UTC
App Version: 1.0.4 (32)
Install Source: Package Installer
Android Version: 7.1.1 (25)
Device Manufacturer: SAMSUNG
Device Model: SM-N950F
Display Resolution: 2094x1080
Display Density (Actual): 420dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by ifoche** [comment] 2018-03-26 09:47
duplicate of #39

**Closed as completed** 2018-03-26 09:48 UTC
Labels: duplicate, invalid
