### ISSUE TITLE
Event UID error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SurveillanceMyanmarApp#40] opened 2018-03-24 09:13 UTC
## User Report
Same error again and if I clicked OK, the case will be removed from both Unsent and Sent tab.

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot764304144.jpg)
## Device Info
```
Time Stamp: 2018-03-24T09:12:20 UTC
App Version: 1.0.4 (32)
Install Source: Package Installer
Android Version: 7.1.1 (25)
Device Manufacturer: SAMSUNG
Device Model: SM-N950F
Display Resolution: 2094x1080
Display Density (Actual): 420dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by ifoche** [comment] 2018-03-26 09:42
duplicate of #39

**Closed as completed** 2018-03-26 09:42 UTC
Labels: duplicate, invalid
